export const HOME_SCREEN = 'HOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const ANIMATED_FLATLIST_SCREEN = 'ANIMATED_FLATLIST_SCREEN';
export const DEMO_SCREEN = 'DEMO_SCREEN';
export const ROOT_HOME_SCREEN = 'ROOT_HOME_SCREEN';
export const SETTING_SCREEN = 'SETTING_SCREEN';
